version: "3"
services:
    mercury_api:
        image: jaredrodriguez/mercury-api:latest
        ports:
            - '9005:9005'
        environment:
            MERCURY_REPO_DIR: mercury-api
            MERCURY_LOG_LEVEL: DEBUG
            API_INVENTORY_INVENTORY_ROUTER: tcp://mercury-inventory:9000
            API_RPC_RPC_ROUTER: tcp://mercury-rpc:9001
        command: mercury-api
networks:
    default:
        external:
            name: mercury_default




